apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHQ4ZW52eHlx
  CLOUDINARY_KEY: MzIyMTc0MjYxNzc5Mjg5
  CLOUDINARY_SECRET: RTVyU2lxaW11TEtFLWlXSUN5Z1dTTEFsY2pF
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZV1JwYm1GeVlYbGhibUV4TVNJc0ltRWlPaUpqYldsaE5HaHhlRFF3YjNNME1tdHpOSE16ZEhSeGVqZzVJbjAuNzBYb2R3Rktnc3cyYWdQY3hENFRnZw===
  DB_URL: bW9uZ29kYitzcnY6Ly9hZGluYXJheWFuYWR1Z2dlbXB1ZGlfZGJfdXNlcjpoSWRyZXpZQXBDdnJxMVY3QGNsdXN0ZXIwLjhhaDBuOWcubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
  SECRET: YWRp
